### ISSUE TITLE
pretty_breaks doesn't seem to respect min.n

### ISSUE THREAD

**Issue by woodwards** [r-lib/scales#206] opened 2019-05-01 00:19 UTC
I have a facet_wrap plot with histograms, lines and points. Some of the facets only have one x-axis break, despite the min.n=2 in pretty_breaks. If I use pretty_breaks with n>2 I get a lot of overlapping breaks. Each facet has a very different x scale.
```
  plot1 <- ggplot(data=prior_df) +
    labs(title="", x="", y="") +
    geom_line(mapping=aes(x=x, y=y), colour=xmid, size=1) +
    geom_histogram(data=gather(post_df), mapping=aes(x=value, y=..density..), fill=xlight) +
    geom_line(mapping=aes(x=x, y=y), colour=xmid, size=1) +
    geom_point(mapping=aes(x=xmap, y=ymap), colour=xdata, size=2) +
    theme_few() +
    theme(panel.spacing.x=unit(10, "mm")) +
    # theme(axis.text=element_text(size=9)) +
    scale_x_continuous(expand=expand_scale(0,0), breaks=pretty_breaks(n=2, min.n=2)) +
    scale_y_continuous(expand=expand_scale(0,0), breaks=NULL) +
    facet_wrap(vars(key), scales="free")
  png( paste(scenario, "/BC_parameter_histograms_BT.png", sep=""),
       width=210*1.5, height=210*1.5, units="mm",
       type="windows", res=600)  
  print(plot1)
  dev.off()
```
![BC_parameter_histograms_BT](https://user-images.githubusercontent.com/30030254/57001129-2e601680-6c0b-11e9-8213-283c020b23dc.png)

**Comment by dpseidel** [comment] 2019-05-01 01:24
Can you please provide a minimal reprex (reproducible example)?  The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: [please help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)!

If you've never heard of a reprex before, start by reading [this post](https://www.tidyverse.org/help/#reprex). Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by woodwards** [comment] 2019-05-01 21:18
``` r
library(tidyverse)
library(scales)
#> 
#> Attaching package: 'scales'
#> The following object is masked from 'package:purrr':
#> 
#>     discard
#> The following object is masked from 'package:readr':
#> 
#>     col_factor

df <- structure(list(key = c("ABASAL", "ABASAL", "ABASAL", "ABASAL", 
"ABASAL", "ABASAL", "ABASAL", "ABASAL", "ABASAL", "ABASAL", "ABASAL", 
"ABASAL", "ABASAL", "ABASAL", "ABASAL", "ABASAL", "ABASAL", "ABASAL", 
"ABASAL", "ABASAL", "ABASAL", "ABASAL", "FGRESSI", "FGRESSI", 
"FGRESSI", "FGRESSI", "FGRESSI", "FGRESSI", "FGRESSI", "FGRESSI", 
"FGRESSI", "FGRESSI", "FGRESSI", "FGRESSI"), x = c(0.001, 0.0082, 
0.00829, 0.00838, 0.00847, 0.00856, 0.00865, 0.00874, 0.00883, 
0.00892, 0.00901, 0.0091, 0.00919, 0.00928, 0.00937, 0.00946, 
0.00955, 0.00964, 0.00973, 0.00982, 0.00991, 0.01, 0.2, 0.206, 
0.212, 0.218, 0.224, 0.23, 0.77, 0.776, 0.782, 0.788, 0.794, 
0.8), y = c(0, 11.0493287641799, 9.52417004372928, 8.13788565579873, 
6.88592012436097, 5.763323666614, 4.76476082369701, 3.88451964303298, 
3.11652152228274, 2.45433185328381, 1.89117164322408, 1.41993034474676, 
1.03318020495593, 0.723192559340674, 0.481956675150222, 0.301202035928486, 
0.172425447313178, 0.0869252360804243, 0.0358466051992872, 0.0102463214066776, 
0.00119660118123218, 0, 0, 0.00490050000000002, 0.0192080000000001, 
0.0423405000000001, 0.073728, 0.1128125, 0.1128125, 0.073728, 
0.0423405, 0.019208, 0.0049005, 0)), row.names = c(NA, -34L), class = c("grouped_df", 
"tbl_df", "tbl", "data.frame"), groups = structure(list(key = c("ABASAL", 
"FGRESSI"), .rows = list(1:22, 23:34)), row.names = c(NA, -2L
), class = c("tbl_df", "tbl", "data.frame"), .drop = TRUE))

plot1 <- ggplot(data=df) +
  geom_line(mapping=aes(x=x, y=y)) +
  scale_x_continuous(breaks=pretty_breaks(n=2, min.n=2)) +
  facet_wrap(vars(key), scales="free")
print(plot1)
```

![](https://i.imgur.com/JFZ7Fel.png)

<sup>Created on 2019-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by dpseidel** [comment] 2019-05-02 00:51
Thanks! I've simplified a bit more so we can see what's going on: 
``` r
library(ggplot2)
library(tibble)
#> Warning: package 'tibble' was built under R version 3.5.2
library(scales)

df <- tibble(x = c(0.2, 0.206,
       0.212, 0.218, 0.224, 0.23, 0.77,
       0.776, 0.782, 0.788, 0.794,
       0.8), y = runif(12))

p <- ggplot(df) + geom_line(aes(x,y)) +
  scale_x_continuous(breaks = pretty_breaks(n = 2, min.n = 2))

p
```

![](https://i.imgur.com/gRpgGPh.png)

When the range of the data is very small, pretty breaks appears not to be respecting the `min.n` argument but actually if we look at the output of `pretty_breaks(n=2, min.n =2)` we can see that it is behaving according to the underlying behavior of pretty -- giving a minimum of 2 intervals. However, 2 out of 3 break values happen to be outside the range of our data. 

``` r
## pretty_breaks gives 2 intervals as expected
scales::pretty_breaks(n=2, min.n =2)(df$x)
#> [1] 0.0 0.5 1.0

##  however, the limits of the scale are too narrow to show them!
layer_scales(p)$x
#> <ScaleContinuousPosition>
#>  Range:   0.2 --  0.8
#>  Limits:  0.2 --  0.8
```

If we look at just the values given for the other group:
``` r
x = c(0.001, 0.0082, 
       0.00829, 0.00838, 0.00847, 0.00856, 0.00865, 0.00874, 0.00883, 
       0.00892, 0.00901, 0.0091, 0.00919, 0.00928, 0.00937, 0.00946, 
       0.00955, 0.00964, 0.00973, 0.00982, 0.00991, 0.01)
pretty_breaks(n=2, min.n = 2)(x)
#>[1] 0.000 0.005 0.010
```
We can see that it just happens that 2 of the pretty breaks exist in the range of the data.


One option for avoiding this could be to define your limits a bit wider, however this likely will not work very well under a free scales facet. 
``` r
## one option: define the limits
ggplot(df) + geom_line(aes(x,y)) +
  scale_x_continuous(breaks = pretty_breaks(n = 2, min.n = 2), 
                     limits = c(0,1))
```

![](https://i.imgur.com/yHebJFQ.png)

Another option would be to try a different breaks function. You can try a different breaks function like `scales::extended_breaks` which might work better for your use case, or you can specify your own function written such that it would return 2 breaks within the range of the data. 
``` r
## second option: try extended breaks or custom function
scales::extended_breaks(n=2)(df$x)
#> [1] 0.2 0.8

ggplot(df) + geom_line(aes(x,y)) +
  scale_x_continuous(breaks = extended_breaks(n = 2))
```

![](https://i.imgur.com/sGFJqMF.png)

<sup>Created on 2019-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Since it does not appear that there is a genuine bug in `pretty_breaks` behavior I am closing this now. If you believe I'm mistaken and there is still a genuine bug within a scales function, please feel free to open a new issue with a minimal reprex.

**Closed by dpseidel** 2019-05-02 00:51 UTC
Labels: reprex

**Comment by dpseidel** [comment] 2019-05-02 00:55
It's also possible you may be able to adjust for your small ranges with one of the other arguments to `pretty` like `shrink.sml`. I have not tested this but it might be right for your use case.

**Comment by woodwards** [comment] 2019-05-02 02:51
Thanks. This almost works:

```
  my_pretty_breaks <- function(n = 5, ...) {
    n_default <- n
    function(x, n = n_default) {
      minx <- min(x)
      maxx <- max(x)
      midx <- (minx+maxx)/2
      x2 <- midx+(x-midx)*0.9
      breaks <- pretty(x2, n, ...)
      names(breaks) <- attr(breaks, "labels")
      breaks
    }
  }
```
