### ISSUE TITLE
Inconsistent behavior for different values of "accuracy" in "percentage()" function

### ISSUE THREAD

**Issue by apsalverda** [r-lib/scales#175] opened 2018-09-04 22:00 UTC
I'm very new to github, so I appreciate any feedback to help improve this issue report!

I get inconsistent results when using the "argument" function of the scales::percentage() function:

```
library(tidyverse)
packageVersion("tidyverse")
packageVersion("scales")
tibble(proportion = seq(0, .1, .001),
       accuracy_point_1 = scales::percent(seq(0, .1, .001), accuracy = .1), 
       accuracy_point_2 = scales::percent(seq(0, .1, .001), accuracy = .2), 
       accuracy_point_01 = scales::percent(seq(0, .1, .001), accuracy = .01), 
       accuracy_point_02 = scales::percent(seq(0, .1, .001), accuracy = .02))
```

results in:

```
> packageVersion("tidyverse")
[1] ‘1.2.1’
> packageVersion("scales")
[1] ‘1.0.0’
# A tibble: 101 x 5
   proportion accuracy_point_1 accuracy_point_2 accuracy_point_01 accuracy_point_02
        <dbl> <chr>            <chr>            <chr>             <chr>            
 1      0     0.0%             0.0%             0.00%             0.00%            
 2      0.001 0.1%             0.0%             0.10%             0.10%            
 3      0.002 0.2%             0.2%             0.20%             0.20%            
 4      0.003 0.3%             0.4%             0.30%             0.30%            
 5      0.004 0.4%             0.4%             0.40%             0.40%            
 6      0.005 0.5%             0.4%             0.50%             0.50%            
 7      0.006 0.6%             0.6%             0.60%             0.60%            
 8      0.007 0.7%             0.8%             0.70%             0.70%            
 9      0.008 0.8%             0.8%             0.80%             0.80%            
10      0.009 0.9%             0.8%             0.90%             0.90%            
# ... with 91 more rows
```

Note the irregular increments in the second column.

I have two additional comments:
1. I came across this issue while I was trying to use the "accuracy" argument to try to control the rounding in the percentage labels in a graph, which came out as "0.0%, 5.0%, etc" whereas I wanted to see rounding to whole numbers: "0%, 5%, etc".  In this context, the interpretation of the value for "accuracy" was not intuitive and quite confusing.  (See examples in code and tibble above.)  I discovered at some point that using "accuracy = 1" produced the desired behavior, but this took me a while to figure out.  For poor souls like me, it would be helpful to reinstate the deprecated "digits" argument!

2. Within a ggplot() call, the "accuracy" argument fails to work with "percentage", but it works with "percentage_format".  Compare:

```
library(tidyverse)
mpg %>%
count(manufacturer) %>%
mutate(percentage_of_cars = n / sum(n)) %>%
ggplot(aes(x = manufacturer,
    y = percentage_of_cars)) +
geom_bar(stat = "identity") +
    scale_y_continuous(breaks = seq(0, 1, .05),
    labels = scales::percent(accuracy = 1))

Error in number(x = x, accuracy = accuracy, scale = scale, prefix = prefix,  : 
  argument "x" is missing, with no default
```
vs.
```
mpg %>%
    count(manufacturer) %>%
    mutate(percentage_of_cars = n / sum(n)) %>%
    ggplot(aes(x = manufacturer,
        y = percentage_of_cars)) +
    geom_bar(stat = "identity") +
    scale_y_continuous(breaks = seq(0, 1, .05),
        labels = scales::percent_format(accuracy = 1))
```

![image](https://user-images.githubusercontent.com/9888903/45060038-51322f00-b06c-11e8-8ab0-677a895cac1c.png)

**Comment by dpseidel** [comment] 2018-09-04 23:18
So as far as I can tell, each of your concerns actually demonstrate expected behavior but I will address them each for clarities sake.  
____
First, 
>Note the irregular increments in the second column.

The  new `accuracy` argument specifies "the value to round to". The "irregular pattern" actually comes from how the `round()` function in baseR rounds 5's, read below:
>Note that for rounding off a 5, the IEC 60559 standard (see also ‘IEEE 754’) is expected to be used, ‘go to the even digit’. Therefore round(0.5) is 0 and round(-1.5) is -2. However, this is dependent on OS services and on representation error (since e.g. 0.15 is not represented exactly, the rounding rule applies to the represented number and not to the printed number, and so round(0.15, 1) could be either 0.1 or 0.2).

I'll show you step by step how things are rounded below. When using `percent()`, `scale = 100` and given `accuracy = .2` what's really happening is this:

``` r
x = seq(0, .1, .001)
accuracy = .2
scale = 100
(rounder = accuracy/scale)
#> [1] 0.002

# step 1, notice all those .5's - they will be rounded to the even digit by `round`
(r <- x/rounder)
#>   [1]  0.0  0.5  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5
#>  [15]  7.0  7.5  8.0  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5
#>  [29] 14.0 14.5 15.0 15.5 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5
#>  [43] 21.0 21.5 22.0 22.5 23.0 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5
#>  [57] 28.0 28.5 29.0 29.5 30.0 30.5 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5
#>  [71] 35.0 35.5 36.0 36.5 37.0 37.5 38.0 38.5 39.0 39.5 40.0 40.5 41.0 41.5
#>  [85] 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5 46.0 46.5 47.0 47.5 48.0 48.5
#>  [99] 49.0 49.5 50.0

# step 2, the "irregular" pattern emerges here
(s <- round(r))
#>   [1]  0  0  1  2  2  2  3  4  4  4  5  6  6  6  7  8  8  8  9 10 10 10 11
#>  [24] 12 12 12 13 14 14 14 15 16 16 16 17 18 18 18 19 20 20 20 21 22 22 22
#>  [47] 23 24 24 24 25 26 26 26 27 28 28 28 29 30 30 30 31 32 32 32 33 34 34
#>  [70] 34 35 36 36 36 37 38 38 38 39 40 40 40 41 42 42 42 43 44 44 44 45 46
#>  [93] 46 46 47 48 48 48 49 50 50

# step 3, multiple by our rounder so that we can get back to the appropriate values
(t <- s * rounder)
#>   [1] 0.000 0.000 0.002 0.004 0.004 0.004 0.006 0.008 0.008 0.008 0.010
#>  [12] 0.012 0.012 0.012 0.014 0.016 0.016 0.016 0.018 0.020 0.020 0.020
#>  [23] 0.022 0.024 0.024 0.024 0.026 0.028 0.028 0.028 0.030 0.032 0.032
#>  [34] 0.032 0.034 0.036 0.036 0.036 0.038 0.040 0.040 0.040 0.042 0.044
#>  [45] 0.044 0.044 0.046 0.048 0.048 0.048 0.050 0.052 0.052 0.052 0.054
#>  [56] 0.056 0.056 0.056 0.058 0.060 0.060 0.060 0.062 0.064 0.064 0.064
#>  [67] 0.066 0.068 0.068 0.068 0.070 0.072 0.072 0.072 0.074 0.076 0.076
#>  [78] 0.076 0.078 0.080 0.080 0.080 0.082 0.084 0.084 0.084 0.086 0.088
#>  [89] 0.088 0.088 0.090 0.092 0.092 0.092 0.094 0.096 0.096 0.096 0.098
#> [100] 0.100 0.100

# and ultimately you are returned:
t * scale
#>   [1]  0.0  0.0  0.2  0.4  0.4  0.4  0.6  0.8  0.8  0.8  1.0  1.2  1.2  1.2
#>  [15]  1.4  1.6  1.6  1.6  1.8  2.0  2.0  2.0  2.2  2.4  2.4  2.4  2.6  2.8
#>  [29]  2.8  2.8  3.0  3.2  3.2  3.2  3.4  3.6  3.6  3.6  3.8  4.0  4.0  4.0
#>  [43]  4.2  4.4  4.4  4.4  4.6  4.8  4.8  4.8  5.0  5.2  5.2  5.2  5.4  5.6
#>  [57]  5.6  5.6  5.8  6.0  6.0  6.0  6.2  6.4  6.4  6.4  6.6  6.8  6.8  6.8
#>  [71]  7.0  7.2  7.2  7.2  7.4  7.6  7.6  7.6  7.8  8.0  8.0  8.0  8.2  8.4
#>  [85]  8.4  8.4  8.6  8.8  8.8  8.8  9.0  9.2  9.2  9.2  9.4  9.6  9.6  9.6
#>  [99]  9.8 10.0 10.0
```

Second, 
>I came across this issue while I was trying to use the "accuracy" argument to try to control the rounding in the percentage labels in a graph, which came out as "0.0%, 5.0%, etc" whereas I wanted to see rounding to whole numbers: "0%, 5%, etc". In this context, the interpretation of the value for "accuracy" was not intuitive and quite confusing. (See examples in code and tibble above.) I discovered at some point that using "accuracy = 1" produced the desired behavior, but this took me a while to figure out. For poor souls like me, it would be helpful to reinstate the deprecated "digits" argument!

When shifting to the generic number formatter we introduced in the 1.0.0 release, we implemented the `accuracy` argument and deprecated the `digits` argument;  `accuracy` is a more flexible solution because it allows uses to specify intermediate values to round to rather than simply whole digits. It might help to examine how  `accuracy`  and `digits` arguments are related: for example, `digits = 0` is the same as `accuracy = 1e0`,  `digits = 1` is the same as `accuracy = 1e-1`,  and `digits = 2` is the same as `accuracy = 1e-2`, etc. 

Finally, 
> Within a ggplot() call, the "accuracy" argument fails to work with "percentage", but it works with "percentage_format".

 The `*_format()` functions return functions themselves which is why you have to use them with the `labels` arguments to scales functions -- these ggplot2 arguments (`labels`, `breaks`, etc.) require either a character vector or a function to be passed.

**Comment by dpseidel** [comment] 2018-09-04 23:18
I am going to close this issue now as those are all expected behaviors, but I hope my explanations were helpful.

**Closed by dpseidel** 2018-09-04 23:18 UTC

**Comment by apsalverda** [comment] 2018-09-05 01:48
@dpseidel Thanks very much for your clear explanations!  I'm still floored (pun intended) about the existence of this rounding standard and its implications, but it's always nice to learn something new.

```
> round(1.5) == round(2.5)
[1] TRUE
```
