### ISSUE TITLE
 unable to load shared object ‘~/’R/win-library/3.2/scales/libs/x64/scales.dll' 

### ISSUE THREAD

**Issue by sobrietie** [r-lib/scales#194] opened 2019-01-10 13:31 UTC
Hi, I'm trying to use  the clusterProfiler package, which requires the scales package (>=0.5.0). However, the binary installed by install.packages() is scales 0.4.1.  So I manually downloaded the 1.0.0 version from CRAN and installed locally. Then I found myself with this unable to load issue. 
I'm using R 3.2.1 with Rstudio 0.98.1062   on Windows 10 X64 platform. 

Is there any way to fix it?
Thank you .

**Comment by dpseidel** [comment] 2019-01-11 00:22
I suspect this is caused by a corrupted install of some form which can occur if you updated scales while you already had it loaded. I would suggest you restart your R session and try reinstalling clusterProfiler and scales 1.0.0 without loading any packages. I was unable to reproduce this issue using R 3.2.5 on RstudioCloud ( I used the source version of BiocInstaller since the most up to date BiocManager requires R > 3.5).  I encountered no issue using clusterProfiler 2.4.3 with scales 1.0.0 on R 3.2.5. 

If you continue to have issues, I would suggest you update your R install and associated packages. BioConductor recommends you use the most up to date version and your setup being several versions behind may be beginning to cause issues as newer packages may drop support for older versions.  As this is not a scales specific issue, I will close this now. In the future, this sort of question may be better suited for the [RStudio Community forum](community.rstudio.com), please try posting there.

**Closed by dpseidel** 2019-01-11 00:22 UTC
