### ISSUE TITLE
percent errors when multiple, separated "Infs" are given as input

### ISSUE THREAD

**Issue by dkesh** [r-lib/scales#265] opened 2020-04-03 15:23 UTC
Using version 1.1.0

This was originally submitted as a comment to #257, but @hadley found that it was unrelated.
```
> percent( Inf )
[1] "Inf"
> percent( c(Inf, Inf) )
[1] "Inf" "Inf"
> percent( c(Inf, 2) )
[1] "Inf"  "200%"
> percent( c(2, Inf) )
[1] "200%" "Inf" 
> percent( c(Inf, 2, Inf) )
Error in if (smallest_diff < sqrt(.Machine$double.eps)) { : 
  missing value where TRUE/FALSE needed
```

**Comment by hadley** [comment] 2020-04-03 15:26
Duplicate of #251 

In the future, please use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Closed by hadley** 2020-04-03 15:26 UTC
